# Generated by Django 5.2 on 2025-04-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedPDF',
        ),
    ]
