# Generated by Django 5.2 on 2025-04-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('converter', '0002_delete_uploadedpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='uploaded_pdfs/')),
                ('he_dao_tao', models.CharField(max_length=100)),
                ('danh_sach_quyet_dinh', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'uploaded_pdf_files',
            },
        ),
    ]
