# Generated by Django 5.2 on 2025-05-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='ten_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
